# Generated by Django 5.2.1 on 2025-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_exchangeproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_exchanged',
            field=models.BooleanField(default=False),
        ),
    ]
